go in smaller steps

diff --git a/.github/workflows/publish_charm.yaml b/.github/workflows/publish_charm.yaml
--- a/.github/workflows/publish_charm.yaml
+++ b/.github/workflows/publish_charm.yaml
@@ -59,113 +59,113 @@ jobs:
           dry_run: true
           github_token: ${{ secrets.GITHUB_TOKEN }}
           charm_dir:  ${{ env.charm_working_directory || env.working_directory }}
-  get-runner-image:
-    name: Get runner image
-    uses: canonical/operator-workflows/.github/workflows/get_runner_image.yaml@test-netbox
-    with:
-      working-directory: ${{ env.charm_working_directory || env.working_directory }}
-  release-charm-libs:
-    name: Release charm libs
-    needs: [ branch-up-to-date-check-enabled ]
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v4.1.1
-      - if: env.charm_working_directory != ''
-        name: Change directory
-        run: |
-          TEMP_DIR=$(mktemp -d)
-          cp -rp ${{env.charm_working_directory}}/. $TEMP_DIR
-          rm -rf .* * || :
-          cp -rp $TEMP_DIR/. .
-          rm -rf $TEMP_DIR
-      - uses: canonical/charming-actions/release-libraries@2.5.0-rc
-        name: Release libs
-        with:
-          credentials: ${{ secrets.CHARMHUB_TOKEN }}
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-  get-run-id:
-    name: Get workflow run id
-    needs: [ branch-up-to-date-check-enabled ]
-    runs-on: ubuntu-22.04
-    outputs:
-      run-id: ${{ env.RUN_ID }}
-    steps:
-      - name: Get workflow run id
-        # TODO THIS IS THE CORRECT ONE if: ${{ github.event_name == 'push' }}
-        if: ${{ github.event_name == 'push'  || github.event_name == 'pull_request' }}
-        shell: bash  
-        run: |
-          # Get commit info
-          TREE_SHA=$(gh api \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/${{ github.repository }}/commits/${GITHUB_SHA} \
-            --jq '.commit.tree.sha')
-          # Get workflow run id from this specific tree id, paginate until found
-          TOTAL_COUNT=$(gh api \
-            --method GET \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/${{ github.repository }}/actions/runs \
-            -f status=completed \
-            -f event=pull_request | jq ".total_count")
-          PER_PAGE=100
-          MAX_PAGES=$(( (TOTAL_COUNT + 99) / $PER_PAGE ))
-          PAGE=1
-          while true; do
-             RESULT=$( gh api \
-              --method GET \
-              -H "Accept: application/vnd.github+json" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              /repos/${{ github.repository }}/actions/runs \
-              -f page=$PAGE \
-              -f per_page=$PER_PAGE \
-              -f status=completed \
-              -f event=pull_request \
-              --jq "[
-                  .workflow_runs[]
-                  | select(.path == \".github/workflows/integration_test.yaml\")
-                  | select(.head_commit.tree_id == \"$TREE_SHA\")
-                ] | max_by(.updated_at) | .id" 
-              )
+  # get-runner-image:
+  #   name: Get runner image
+  #   uses: canonical/operator-workflows/.github/workflows/get_runner_image.yaml@test-netbox
+  #   with:
+  #     working-directory: ${{ env.charm_working_directory || env.working_directory }}
+  # release-charm-libs:
+  #   name: Release charm libs
+  #   needs: [ branch-up-to-date-check-enabled ]
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v4.1.1
+  #     - if: env.charm_working_directory != ''
+  #       name: Change directory
+  #       run: |
+  #         TEMP_DIR=$(mktemp -d)
+  #         cp -rp ${{env.charm_working_directory}}/. $TEMP_DIR
+  #         rm -rf .* * || :
+  #         cp -rp $TEMP_DIR/. .
+  #         rm -rf $TEMP_DIR
+  #     - uses: canonical/charming-actions/release-libraries@2.5.0-rc
+  #       name: Release libs
+  #       with:
+  #         credentials: ${{ secrets.CHARMHUB_TOKEN }}
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  # get-run-id:
+  #   name: Get workflow run id
+  #   needs: [ branch-up-to-date-check-enabled ]
+  #   runs-on: ubuntu-22.04
+  #   outputs:
+  #     run-id: ${{ env.RUN_ID }}
+  #   steps:
+  #     - name: Get workflow run id
+  #       # TODO THIS IS THE CORRECT ONE if: ${{ github.event_name == 'push' }}
+  #       if: ${{ github.event_name == 'push'  || github.event_name == 'pull_request' }}
+  #       shell: bash  
+  #       run: |
+  #         # Get commit info
+  #         TREE_SHA=$(gh api \
+  #           -H "Accept: application/vnd.github+json" \
+  #           -H "X-GitHub-Api-Version: 2022-11-28" \
+  #           /repos/${{ github.repository }}/commits/${GITHUB_SHA} \
+  #           --jq '.commit.tree.sha')
+  #         # Get workflow run id from this specific tree id, paginate until found
+  #         TOTAL_COUNT=$(gh api \
+  #           --method GET \
+  #           -H "Accept: application/vnd.github+json" \
+  #           -H "X-GitHub-Api-Version: 2022-11-28" \
+  #           /repos/${{ github.repository }}/actions/runs \
+  #           -f status=completed \
+  #           -f event=pull_request | jq ".total_count")
+  #         PER_PAGE=100
+  #         MAX_PAGES=$(( (TOTAL_COUNT + 99) / $PER_PAGE ))
+  #         PAGE=1
+  #         while true; do
+  #            RESULT=$( gh api \
+  #             --method GET \
+  #             -H "Accept: application/vnd.github+json" \
+  #             -H "X-GitHub-Api-Version: 2022-11-28" \
+  #             /repos/${{ github.repository }}/actions/runs \
+  #             -f page=$PAGE \
+  #             -f per_page=$PER_PAGE \
+  #             -f status=completed \
+  #             -f event=pull_request \
+  #             --jq "[
+  #                 .workflow_runs[]
+  #                 | select(.path == \".github/workflows/integration_test.yaml\")
+  #                 | select(.head_commit.tree_id == \"$TREE_SHA\")
+  #               ] | max_by(.updated_at) | .id" 
+  #             )
            
-              if [[ -n $RESULT ]]; then
-                  RUN_ID=$RESULT
-                  break
-              fi
-              if [[ "PAGE" -eq "$MAX_PAGES" ]]; then
-                  echo "::error::No workflow run id found for specific tree id"
-                  exit 1
-              fi
-              ((PAGE++))
-          done
+  #             if [[ -n $RESULT ]]; then
+  #                 RUN_ID=$RESULT
+  #                 break
+  #             fi
+  #             if [[ "PAGE" -eq "$MAX_PAGES" ]]; then
+  #                 echo "::error::No workflow run id found for specific tree id"
+  #                 exit 1
+  #             fi
+  #             ((PAGE++))
+  #         done
 
-          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
-        env:
-          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
-      - name: Get current run id
-        # TODO THIS IS THE CORRECT ONE: if: ${{ github.event_name == 'pull_request' }}
-        if: false
-        shell: bash  
-        run: |
-          echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
-  get-images:
-    name: Get images
-    runs-on: ubuntu-22.04
-    outputs:
-      images: ${{ env.IMAGES }}
-    steps:
-      - uses: actions/checkout@v4.1.1
-      - name: Get images
-        working-directory: ${{ inputs.working-directory }}
-        run: |
-          lines=$(find . -type f -name rockcraft.yaml | wc -l)
-          if [ $lines -ne 0 ]; then
-            IMAGES=$(find . -type f -name rockcraft.yaml | xargs -l yq '.name' | jq -Rsc '. / "\n" - [""]')
-          else
-            IMAGES=$(ls *.Dockerfile 2> /dev/null | sed s/\.Dockerfile// |  jq -Rsc '. / "\n" - [""]')
-          fi
-          echo "IMAGES=$IMAGES" >> $GITHUB_ENV
+  #         echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
+  #     - name: Get current run id
+  #       # TODO THIS IS THE CORRECT ONE: if: ${{ github.event_name == 'pull_request' }}
+  #       if: false
+  #       shell: bash  
+  #       run: |
+  #         echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
+  # get-images:
+  #   name: Get images
+  #   runs-on: ubuntu-22.04
+  #   outputs:
+  #     images: ${{ env.IMAGES }}
+  #   steps:
+  #     - uses: actions/checkout@v4.1.1
+  #     - name: Get images
+  #       working-directory: ${{ inputs.working-directory }}
+  #       run: |
+  #         lines=$(find . -type f -name rockcraft.yaml | wc -l)
+  #         if [ $lines -ne 0 ]; then
+  #           IMAGES=$(find . -type f -name rockcraft.yaml | xargs -l yq '.name' | jq -Rsc '. / "\n" - [""]')
+  #         else
+  #           IMAGES=$(ls *.Dockerfile 2> /dev/null | sed s/\.Dockerfile// |  jq -Rsc '. / "\n" - [""]')
+  #         fi
+  #         echo "IMAGES=$IMAGES" >> $GITHUB_ENV
   # publish-images:
   #   name: Publish images to charmhub
   #   runs-on: ${{ needs.get-runner-image.outputs.runs-on }}
